<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 (x64) (http://www.altova.com) by Victor Rozhkov (BFT-Razrabotka) -->
<xs:schema xmlns="http://пф.рф/ЗОДСВ/2023-01-10" xmlns:УТ6="http://пф.рф/УТ/2023-01-10"
	xmlns:АФ6="http://пф.рф/АФ/2023-01-10" xmlns:ДС6="http://пф.рф/ВС/ДоСВ/типы/2023-01-10"
	xmlns:sig="http://iis.ecp.ru/SignInfo/2023-01-10" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:ns1="http://www.w3.org/2000/09/xmldsig#" targetNamespace="http://пф.рф/ЗОДСВ/2023-01-10"
	elementFormDefault="qualified" version="2.0">
	<xs:import namespace="http://пф.рф/УТ/2023-01-10" schemaLocation="УнифТипы_2023-01-10.xsd"/>
	<xs:import namespace="http://пф.рф/АФ/2023-01-10" schemaLocation="ТипыАФ_2023-01-10.xsd"/>
	<xs:import namespace="http://пф.рф/ВС/ДоСВ/типы/2023-01-10"
		schemaLocation="ТипыДоСВ_2023-01-10.xsd"/>
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#"
		schemaLocation="xmldsig_core_schema.xsd"/>
	<xs:import namespace="http://iis.ecp.ru/SignInfo/2023-01-10"
		schemaLocation="SignInfo_2023-01-10.xsd"/>
	<xs:annotation>
		<xs:documentation>
			Заявление о добровольном вступлении в правоотношения по обязательному пенсионному страхованию
		</xs:documentation>
	</xs:annotation>
	<xs:element name="ЭДПФР">
		<xs:annotation>
			<xs:documentation>Корневой элемент. Содержит сведения самого документа и служебную информацию об электронном документе.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ЗОДСВ">
					<xs:annotation>
						<xs:documentation>Заявление о добровольном вступлении в правоотношения по обязательному пенсионному страхованию</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ТОПФР" type="УТ6:ТипТОПФР">
								<xs:annotation>
									<xs:documentation>Блок сведений о территориальном органе ПФР, в который подается заявление</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Подпункт">
								<xs:annotation>
									<xs:documentation>Номер подпункта пункта 1 статьи 29 Федерального закона от 15 декабря 2001 г. № 167-ФЗ  «Об обязательном пенсионном страховании в Российской Федерации»,  в соответствии с которым заявитель вступает в правоотношения по обязательному пенсионному страхованию. Возможные значения:
										1,
										2,
										3,
										5,
										6,
										7</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:enumeration value="1"/>
										<xs:enumeration value="2"/>
										<xs:enumeration value="3"/>
										<xs:enumeration value="5"/>
										<xs:enumeration value="6"/>
										<xs:enumeration value="7"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Заявитель">
								<xs:annotation>
									<xs:documentation>Блок сведений о заявителе</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="УТ6:ФИО">
											<xs:annotation>
												<xs:documentation>Фамилия, имя, отчество заявителя</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:group ref="УТ6:ГрДатаРождения">
											<xs:annotation>
												<xs:documentation>Дата рождения заявителя</xs:documentation>
											</xs:annotation>
										</xs:group>
										<xs:element ref="УТ6:МестоРождения">
											<xs:annotation>
												<xs:documentation>Место рождения заявителя</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="УТ6:СНИЛС">
											<xs:annotation>
												<xs:documentation>Страховой номер индивидуального лицевого счета заявителя</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="УТ6:ИНН">
											<xs:annotation>
												<xs:documentation>ИНН</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="ДС6:КодНО" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Код налогового органа по месту жительства физического лица, добровольно вступающего в правоотношения</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="УТ6:Гражданства" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Гражданство заявителя</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="УТ6:АдресРегистрации" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Почтовый адрес места жительства в Российской Федерации</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="ПроживаниеЗаПределамиРФ" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Блок сведений о проживании за пределами Российской Федерации</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
												<xs:element name="Страна"
												type="УТ6:ТипНепустаяСтрока">
												<xs:annotation>
												<xs:documentation>Страна постоянного проживания до прибытия в Российскую Федерацию (для иностранных граждан)</xs:documentation>
												</xs:annotation>
												</xs:element>
												<xs:element name="ДатаВыезда" type="xs:date">
												<xs:annotation>
												<xs:documentation>Дата предполагаемого выезда за пределы территории Российской Федерации (для иностранных граждан)</xs:documentation>
												</xs:annotation>
												</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="АдресУведомления" type="УТ6:ТипАдресОбщий"
											minOccurs="0">
											<xs:annotation>
												<xs:documentation>Почтовый адрес для направления уведомления о регистрации страхователя, добровольно вступившего в правоотношения по обязательному пенсионному страхованию</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="УТ6:Телефон" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Номер телефона заявителя</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="УТ6:АдресЭлПочты" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Представитель" type="УТ6:ТипПредставительФЛ-ЮЛ"
								minOccurs="0">
								<xs:annotation>
									<xs:documentation>Сведения о представителе застрахованного лица</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Категория">
								<xs:annotation>
									<xs:documentation>Основание для постановки на учет в качестве страхователя. Возможные значения:
										1 – Гражданин Российской Федерации, работающий за пределами территории Российской Федерации, в целях уплаты страховых взносов в Пенсионный фонд Российской Федерации за себя
										2 – Физическое лицо, в целях уплаты страховых взносов за другое физическое лицо, за которое не осуществляется уплата страховых взносов страхователем в соответствии с Федеральным законом от 15 декабря 2001 г. № 167-ФЗ «Об обязательном пенсионном страховании в Российской Федерации» и частью второй Налогового кодекса Российской Федерации
										3 – Индивидуальный предприниматель, осуществляющий уплату страховых взносов в фиксированном размере, в части, превышающей этот размер
										4 – Нотариус, занимающийся частной практикой и осуществляющий уплату страховых взносов в фиксированном размере, в части, превышающей этот размер
										5 – Адвокат, осуществляющий уплату страховых взносов в фиксированном размере, в части, превышающей этот размер
										6 - Арбитражный управляющий, осуществляющий уплату страховых взносов в фиксированном размере, в части, превышающей этот размер
										7 – Иные лица, занимающиеся частной практикой и осуществляющие уплату страховых взносов в фиксированном размере, в части, превышающей этот размер
										8 – Физическое лицо в целях уплаты страховых взносов в Пенсионный фонд Российской Федерации за себя, постоянно или временно проживающее на территории Российской Федерации, на которое не распространяется обязательное пенсионное страхование в соответствии с Федеральным законом от 15 декабря 2001 г. № 167-ФЗ «Об обязательном пенсионном страховании в Российской Федерации», за исключением лиц, указанных в подпунктах 6 и 7 пункта 1 статьи 29 данного закона
										9 – Физическое лицо в целях уплаты страховых взносов в Пенсионный фонд Российской Федерации за себя, применяющее специальный налоговый режим «Налог на профессиональный доход», постоянно или временно проживающее на территории Российской Федерации
										10 – Физическое лицо из числа адвокатов, являющихся получателями пенсии за выслугу лет или пенсии по инвалидности в соответствии с Законом Российской Федерации от 12 февраля 1993 г. № 4468-1 «О пенсионном обеспечении лиц, проходивших военную службу, службу в органах внутренних дел, Государственной противопожарной службе, органах по контролю за оборотом наркотических средств и психотропных веществ, учреждениях и органах уголовно-исполнительной системы, войсках национальной гвардии Российской Федерации, органах принудительного исполнения Российской Федерации, и их семей» в целях уплаты страховых взносов в Пенсионный фонд Российской Федерации за себя
										</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="1"/>
										<xs:enumeration value="2"/>
										<xs:enumeration value="3"/>
										<xs:enumeration value="4"/>
										<xs:enumeration value="5"/>
										<xs:enumeration value="6"/>
										<xs:enumeration value="7"/>
										<xs:enumeration value="8"/>
										<xs:enumeration value="9"/>
										<xs:enumeration value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:choice minOccurs="0">
								<xs:element name="РаботаВнеРФ">
									<xs:annotation>
										<xs:documentation>Блок сведений по гражданину РФ, работающему заграницей</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:sequence>
											<xs:element name="КодДокумента">
												<xs:annotation>
												<xs:documentation>Код документа, подтверждающего факт работы за пределами территории РФ, либо документа, подтверждающего факт приглашения на работу за пределы территории РФ. Возможные значения:
																		663	Документ, подтверждающий факт работы за пределами территории Российской Федерации;
																		664	Документ, подтверждающий факт приглашения на работу за пределы территории Российской Федерации.
																		665 Иной документ, подтверждающий факт работы за пределами РФ
														</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
												<xs:restriction base="xs:integer">
												<xs:enumeration value="663"/>
												<xs:enumeration value="664"/>
												<xs:enumeration value="665"/>
												</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="НаименованиеДокумента"
												type="УТ6:ТипНепустаяСтрока">
												<xs:annotation>
												<xs:documentation>Наименование правоустанавливающего документа</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element ref="УТ6:КемВыдан">
												<xs:annotation>
												<xs:documentation>Наименование  органа, выдавшего правоустанавливающий документ</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element name="Реквизиты"
												type="УТ6:ТипРеквизитыДокумента">
												<xs:annotation>
												<xs:documentation>Блок сведений о реквизитах документа</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element ref="УТ6:СрокДействия" minOccurs="0">
												<xs:annotation>
												<xs:documentation>Дата окончания срока действия документа. Если дата окончания не указана, документ выдан бессрочно</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element name="СрокДоговора"
												type="УТ6:ТипОткрытыйВременнойПериод" minOccurs="0">
												<xs:annotation>
												<xs:documentation>Блок сведений о сроке действия трудового договора (контракта) на работу за пределами территории Российской Федерации</xs:documentation>
												</xs:annotation>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="НалогНаПрофессиональныйДоход">
									<xs:annotation>
										<xs:documentation>Блок сведений о постановке на учет в налоговом органе в качестве налогоплательщика, применяющего специальный налоговый режим «Налог на профессиональный доход»</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:sequence>
											<xs:element name="Сведения" minOccurs="0">
												<xs:annotation>
												<xs:documentation>Сведения (информация), подтверждающие факт постановки на учет в налоговом органе в качестве налогоплательщика, применяющего специальный налоговый режим «Налог на профессиональный доход»</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
												<xs:restriction base="УТ6:ТипНепустаяСтрока">
												<xs:maxLength value="500"/>
												</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="Дата" type="xs:date">
												<xs:annotation>
												<xs:documentation>Дата постановки на учет в налоговом органе в качестве налогоплательщика, применяющего специальный налоговый режим «Налог на профессиональный доход»</xs:documentation>
												</xs:annotation>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="ЛицоУплатаСВ">
									<xs:annotation>
										<xs:documentation>Блок сведений о физическом лице, за которое осуществляется уплата страховых взносов</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:sequence>
											<xs:element ref="УТ6:ФИО">
												<xs:annotation>
												<xs:documentation>Фамилия, имя, отчество (при наличии) физического лица, за которое осуществляется уплата страховых взносов</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element ref="УТ6:АдресРегистрации">
												<xs:annotation>
												<xs:documentation>Почтовый адрес места жительства физического лица, за которое осуществляется уплата страховых взносов</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element ref="УТ6:УдостоверяющийДокумент">
												<xs:annotation>
												<xs:documentation>Блок сведений о документе, удостоверяющем личность физического лица, за которое осуществляется уплата страховых взносов</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element ref="УТ6:СНИЛС">
												<xs:annotation>
												<xs:documentation>Страховой номер индивидуального лицевого счета застрахованного лица, за которое осуществляется уплата страховых взносов</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element ref="УТ6:ДатаРождения" minOccurs="0">
												<xs:annotation>
												<xs:documentation>Дата рождения физического лица</xs:documentation>
												</xs:annotation>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:sequence>
									<xs:element name="ЛицоАдвокат">
										<xs:annotation>
											<xs:documentation>Блок сведений о документе, подтверждающем факт постановки на учет в налоговом органе физического лица в качестве адвоката</xs:documentation>
										</xs:annotation>
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Сведения"
												type="УТ6:ТипНепустаяСтрока">
												<xs:annotation>
												<xs:documentation>Сведения (информация), подтверждающие факт постановки на учет в налоговом органе физического лица в качестве адвоката</xs:documentation>
												</xs:annotation>
												</xs:element>
												<xs:element name="Дата" type="xs:date">
												<xs:annotation>
												<xs:documentation>Дата постановки на учет в налоговом органе в качестве адвоката</xs:documentation>
												</xs:annotation>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
									<xs:element name="ДокументОПенсии">
										<xs:annotation>
											<xs:documentation>Блок сведений о документе, подтверждающие факт получения пенсии за выслугу лет или пенсии по  инвалидности в соответствии с Законом Российской Федерации от 12 февраля 1993 г. № 4468-1 «О пенсионном обеспечении лиц, проходивших военную службу, службу в органах внутренних дел, Государственной противопожарной службе, органах по контролю за оборотом наркотических средств и психотропных веществ, учреждениях и органах уголовно-исполнительной системы, войсках национальной гвардии Российской Федерации, органах принудительного исполнения Российской Федерации, и их семей»</xs:documentation>
										</xs:annotation>
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Сведения"
												type="УТ6:ТипНепустаяСтрока">
												<xs:annotation>
												<xs:documentation>Сведения (информация), подтверждающие факт получения пенсии за выслугу лет или пенсии по  инвалидности в соответствии с Законом Российской Федерации от 12 февраля 1993 г. № 4468-1 «О пенсионном обеспечении лиц, проходивших военную службу, службу в органах внутренних дел, Государственной противопожарной службе, органах по контролю за оборотом наркотических средств и психотропных веществ, учреждениях и органах уголовно-исполнительной системы, войсках национальной гвардии Российской Федерации, органах принудительного исполнения Российской Федерации, и их семей»</xs:documentation>
												</xs:annotation>
												</xs:element>
												<xs:element name="Дата" type="xs:date">
												<xs:annotation>
												<xs:documentation>Дата установления пенсии</xs:documentation>
												</xs:annotation>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:choice>
							<xs:element name="Информирование" maxOccurs="4">
								<xs:annotation>
									<xs:documentation>Уведомления о регистрации лица, добровольно вступившего в правоотношения по обязательному пенсионному страхованию :
														6 -Лично
														7 - Направить по почте
														5 - Направить в форме электронного документа при направлении заявления через Единый портал	
														4 - Направить по электронной почте						
									</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:enumeration value="6"/>
										<xs:enumeration value="7"/>
										<xs:enumeration value="5"/>
										<xs:enumeration value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Дата" type="xs:date">
								<xs:annotation>
									<xs:documentation>Дата заполнения заявления</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="УникальныйВидИнофрмирования">
						<xs:selector xpath="Информирование"/>
						<xs:field xpath="."/>
					</xs:unique>
				</xs:element>
				<xs:element name="СлужебнаяИнформация" type="АФ6:ТипСлужебнаяИнформация"
					minOccurs="0">
					<xs:annotation>
						<xs:documentation>Служебная информация об электронном документе</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="ns1:Signature" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Электронная подпись (ЭП). Электронный документ, для которого законодательством Российской Федерации предусмотрена юридически значимая подпись, должен быть подписан усиленной квалифицированной электронной подписью в соответствии со спецификацией XMLDSig</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="sig:SignInfo" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
